name: Build and Deploy Socket.io Server to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

# ✅ Required for Azure OIDC Login
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: socket

      - name: Zip app for deployment
        run: zip -r socketapp.zip . -x '*.git*' 'node_modules/*'
        working-directory: socket

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: socketapp
          path: socket/socketapp.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: socketapp

      - name: Unzip artifact
        run: unzip socketapp.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_59065879A5814EB29A43D9844A75E168 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_39E43A2612E841FEBEB4A06351C633E3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C5DD901C3C4C4A57A5EF2CDB8D328D0C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'socketrealestate'
          slot-name: 'Production'
          package: .
